service:
  name: cloud-chat

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  webpack:
    packager: yarn
    includeModules:
      forceExclude:
        - aws-sdk
  serviceId: ${self:service.name}-${self:provider.stage}
  references: ${file(../serverless/resources.yml):references}

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs10.x
  websocketsApiName: ${self:provider.stage}-cloud-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iamRoleStatements: ${file(../serverless/role.yml)}
  environment: ${file(../serverless/environment.yml)}

functions: ${file(../serverless/functions.yml)}

resources:
  Resources: ${file(../serverless/resources.yml):Resources}
