service:
  name: cloud-chat

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs10.x
  websocketsApiName: ${self:provider.stage}-cloud-chat-api
  websocketApiRouteSelectionExpression: $request.body.action

functions:
  manageConnection:
    handler: src/manageConnection.handler
    events:
      - websocket: $connect
      - websocket: $disconnect
  defaultHandler:
    handler: src/defaultHandler.handler
    events:
      - websocket: $default
